include $(THEOS)/makefiles/common.mk

TWEAK_NAME = TypeStatusPlusSnapchat
TypeStatusPlusSnapchat_FILES = Tweak.xm
TypeStatusPlusSnapchat_EXTRA_FRAMEWORKS = TypeStatusPlusProvider

include $(THEOS_MAKE_PATH)/tweak.mk
