#!/bin/bash
set -e

# relaunch assertiond so we get injected into it, but not when we’re
# upgrading or it’ll get stopped again by postinst
if [[ $1 != upgrade ]]; then
	launchctl stop com.apple.assertiond
else
	:
fi
