include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = Music
Music_FILES = $(wildcard *.m)
Music_PRIVATE_FRAMEWORKS = MediaRemote
Music_EXTRA_FRAMEWORKS = TypeStatusPlusProvider
Music_INSTALL_PATH = /Library/TypeStatus/Providers

include $(THEOS_MAKE_PATH)/bundle.mk