include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = TypeStatusWatch

TypeStatusWatch_FILES = $(wildcard *.m)
TypeStatusWatch_INSTALL_PATH = /Applications/TypeStatus.app/PlugIns
TypeStatusWatch_BUNDLE_EXTENSION = appex

SUBPROJECTS = watch-app

include $(THEOS_MAKE_PATH)/bundle.mk
include $(THEOS_MAKE_PATH)/aggregate.mk
