include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = TypeStatusPlusSlackPrefs
TypeStatusPlusSlackPrefs_FILES = HBTSPlusSlackRootListController.m
TypeStatusPlusSlackPrefs_INSTALL_PATH = /Library/PreferenceBundles
TypeStatusPlusSlackPrefs_FRAMEWORKS = UIKit
TypeStatusPlusSlackPrefs_PRIVATE_FRAMEWORKS = Preferences
TypeStatusPlusSlackPrefs_EXTRA_FRAMEWORKS = CepheiPrefs

include $(THEOS_MAKE_PATH)/bundle.mk