include $(THEOS)/makefiles/common.mk

TWEAK_NAME = TypeStatusPlusAssertiond
TypeStatusPlusAssertiond_FILES = Tweak.x
TypeStatusPlusAssertiond_PRIVATE_FRAMEWORKS = BaseBoard

include $(THEOS_MAKE_PATH)/tweak.mk
