include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = TypeStatusPlus
TypeStatusPlus_FILES = main.m
TypeStatusPlus_FRAMEWORKS = UIKit
TypeStatusPlus_ARCHS = armv7

include $(THEOS_MAKE_PATH)/application.mk
