include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = TypeStatusPlusProvider
TypeStatusPlusProvider_FILES = $(wildcard *.m)
TypeStatusPlusProvider_INSTALL_PATH = /Library/PreferenceBundles
TypeStatusPlusProvider_FRAMEWORKS = UIKit
TypeStatusPlusProvider_PRIVATE_FRAMEWORKS = Preferences
TypeStatusPlusProvider_EXTRA_FRAMEWORKS = CepheiPrefs

include $(THEOS_MAKE_PATH)/bundle.mk
