include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = TypeStatusPlusSnapchatPrefs
TypeStatusPlusSnapchatPrefs_FILES = HBTSPlusSnapchatRootListController.m
TypeStatusPlusSnapchatPrefs_INSTALL_PATH = /Library/PreferenceBundles
TypeStatusPlusSnapchatPrefs_FRAMEWORKS = UIKit
TypeStatusPlusSnapchatPrefs_PRIVATE_FRAMEWORKS = Preferences
TypeStatusPlusSnapchatPrefs_EXTRA_FRAMEWORKS = CepheiPrefs

include $(THEOS_MAKE_PATH)/bundle.mk