include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = TypeStatusPlusMusicPrefs
TypeStatusPlusMusicPrefs_FILES = HBTSPlusMusicRootListController.m
TypeStatusPlusMusicPrefs_INSTALL_PATH = /Library/PreferenceBundles
TypeStatusPlusMusicPrefs_FRAMEWORKS = UIKit
TypeStatusPlusMusicPrefs_PRIVATE_FRAMEWORKS = Preferences
TypeStatusPlusMusicPrefs_EXTRA_FRAMEWORKS = CepheiPrefs

include $(THEOS_MAKE_PATH)/bundle.mk