include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = TypeStatusPlusMessengerPrefs
TypeStatusPlusMessengerPrefs_FILES = HBTSPlusMessengerRootListController.m
TypeStatusPlusMessengerPrefs_INSTALL_PATH = /Library/PreferenceBundles
TypeStatusPlusMessengerPrefs_FRAMEWORKS = UIKit
TypeStatusPlusMessengerPrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk