include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = Snapchat
Snapchat_FILES = $(wildcard *.m)
Snapchat_EXTRA_FRAMEWORKS = TypeStatusPlusProvider
Snapchat_INSTALL_PATH = /Library/TypeStatus/Providers

include $(THEOS_MAKE_PATH)/bundle.mk
