include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = Skype
Skype_FILES = $(wildcard *.m)
Skype_EXTRA_FRAMEWORKS = TypeStatusPlusProvider
Skype_INSTALL_PATH = /Library/TypeStatus/Providers

include $(THEOS_MAKE_PATH)/bundle.mk
