include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = TypeStatusPlusWhatsappPrefs
TypeStatusPlusWhatsappPrefs_FILES = HBTSPlusWhatsappRootListController.m
TypeStatusPlusWhatsappPrefs_INSTALL_PATH = /Library/PreferenceBundles
TypeStatusPlusWhatsappPrefs_FRAMEWORKS = UIKit
TypeStatusPlusWhatsappPrefs_PRIVATE_FRAMEWORKS = Preferences
TypeStatusPlusWhatsappPrefs_EXTRA_FRAMEWORKS = CepheiPrefs

include $(THEOS_MAKE_PATH)/bundle.mk