include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = TypeStatusPlusSkypePrefs
TypeStatusPlusSkypePrefs_FILES = HBTSPlusSkypeRootListController.m
TypeStatusPlusSkypePrefs_INSTALL_PATH = /Library/PreferenceBundles
TypeStatusPlusSkypePrefs_FRAMEWORKS = UIKit
TypeStatusPlusSkypePrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk