include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = TypeStatusPlusTelegramPrefs
TypeStatusPlusTelegramPrefs_FILES = HBTSPlusTelegramRootListController.m
TypeStatusPlusTelegramPrefs_INSTALL_PATH = /Library/PreferenceBundles
TypeStatusPlusTelegramPrefs_FRAMEWORKS = UIKit
TypeStatusPlusTelegramPrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk