include $(THEOS)/makefiles/common.mk

FRAMEWORK_NAME = TypeStatusPlus
TypeStatusPlus_FILES = HBTSPlusProvider.m
TypeStatusPlus_PUBLIC_HEADERS = HBTSPlusProvider.h
TypeStatusPlus_EXTRA_FRAMEWORKS = Cephei
TypeStatusPlus_CFLAGS = -include Global.h

include $(THEOS_MAKE_PATH)/framework.mk