include $(THEOS)/makefiles/common.mk

FRAMEWORK_NAME = TypeStatusPlusProvider
TypeStatusPlusProvider_FILES = Loading.xm HBTSPlusProvider.m
TypeStatusPlusProvider_PUBLIC_HEADERS = HBTSPlusProvider.h
TypeStatusPlusProvider_EXTRA_FRAMEWORKS = Cephei
TypeStatusPlusProvider_LIBRARIES = substrate
TypeStatusPlusProvider_CFLAGS = -include ../Global.h

include $(THEOS_MAKE_PATH)/framework.mk